leadtrekker.leadtrekker_source_id:
  type: mapping
  label: Leadtrekker Source ID link to webform.
  mapping:
    id:
      type: text
    source_id:
      type: text

leadtrekker.leadtrekker_component:
  type: mapping
  label: Component Source link to webform element id.
  mapping:
    id:
      type: text
    component:
      type: text