<?php
/**
 * @file
 * An example field using the Field Types API.
 */

/**
 * @defgroup source_id_field Example: Field Types API
 * @ingroup examples
 * @{
 * Examples using Field Types API.
 *
 * This is updated from Barry Jaspan's presentation at Drupalcon Paris,
 * @link http://acquia.com/community/resources/acquia-tv/intro-field-api-module-developers Video Presentation @endlink
 *
 * Providing a field requires:
 * - Defining a field:
 *   - hook_field_info()
 *   - hook_field_schema()
 *   - hook_field_validate()
 *   - hook_field_is_empty()
 *
 * - Defining a formatter for the field (the portion that outputs the field for
 *   display):
 *   - hook_field_formatter_info()
 *   - hook_field_formatter_view()
 *
 * - Defining a widget for the edit form:
 *   - hook_field_widget_info()
 *   - hook_field_widget_form()
 *
 * Our module defines the field in source_id_field_info(),
 * source_id_field_validate() and source_id_field_field_is_empty().
 * source_id_field_schema() is implemented in source_id_field.install.
 *
 * Our module sets up a formatter in source_id_field_formatter_info() and
 * source_id_field_field_formatter_view(). These are the API hooks that present
 * formatted and themed output to the user.
 *
 * And finally, our module defines the widget in
 * source_id_field_widget_info() and source_id_field_widget_form().
 * The widget is the form element used to receive input from the user
 * when the field is being populated.
 *
 * @see field_types
 * @see field
 */

/***************************************************************
 * Field Type API hooks
 ***************************************************************/

/**
 * Implements hook_field_info().
 *
 * Provides the description of the field.
 */
function source_id_field_info() {
  return array(
    // We name our field as the associative name of the array.
    'source_id' => array(
      'label' => t('Leadtrekker Source ID'),
      'description' => t('Associates nodes with Leadtrekker Source IDs.'),
      'default_widget' => 'source_id_widget',
      'default_formatter' => 'source_id_text',
    ),
  );
}

/**
 * Implements hook_field_validate().
 *
 * This hook gives us a chance to validate content that's in our
 * field. We're really only interested in the $items parameter, since
 * it holds arrays representing content in the field we've defined.
 * We want to verify that the items only contain RGB hex values like
 * this: #RRGGBB. If the item validates, we do nothing. If it doesn't
 * validate, we add our own error notification to the $errors parameter.
 *
 * @see source_id_field_field_widget_error()
 */
function source_id_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
  foreach ($items as $delta => $item) {
    if (!empty($item['source_id'])) {
      if (!is_numeric($item['source_id'])) {
        $errors[$field['field_name']][$langcode][$delta][] = array(
          'error' => 'source_id_field_invalid',
          'message' => t('Source IDs have to be integers.'),
        );
      }
    }
  }
}


/**
 * Implements hook_field_is_empty().
 *
 * hook_field_is_empty() is where Drupal asks us if this field is empty.
 * Return TRUE if it does not contain data, FALSE if it does. This lets
 * the form API flag an error when required fields are empty.
 */
function source_id_field_is_empty($item, $field) {
  return empty($item['source_id']);
}

/**
 * Implements hook_field_formatter_info().
 *
 * We need to tell Drupal that we have two different types of formatters
 * for this field. One will change the text color, and the other will
 * change the background color.
 *
 * @see source_id_field_field_formatter_view()
 */
function source_id_field_formatter_info() {
  return array(
    // This formatter just displays the hex value in the color indicated.
    'source_id_text' => array(
      'label' => t('Simple text-based formatter'),
      'field types' => array('source_id'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 *
 * Two formatters are implemented.
 * - source_id_field_text just outputs markup indicating the color that
 *   was entered and uses an inline style to set the text color to that value.
 * - source_id_field_color_background does the same but also changes the
 *   background color of div.region-content.
 *
 * @see source_id_field_field_formatter_info()
 */
function source_id_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  switch ($display['type']) {
    // This formatter simply outputs the field as text and with a color.
    case 'source_id_text':
      foreach ($items as $delta => $item) {
        $element[$delta] = array(
          // We create a render array to produce the desired output (integer).
          '#type' => 'html_tag',
          '#tag' => 'p',
          '#value' => $item['source_id'],
        );
      }
      break;
  }

  return $element;
}

/**
 * Implements hook_field_widget_info().
 *
 * Three widgets are provided.
 * - A simple text-only widget where the user enters the '#ffffff'.
 *
 * These widget types will eventually show up in hook_field_widget_form,
 * where we will have to flesh them out.
 *
 * @see source_id_widget_form()
 */
function source_id_field_widget_info() {
  return array(
    'source_id_widget' => array(
      'label' => t('Source ID as integer.'),
      'field types' => array('source_id'),
    ),
  );
}

/**
 * Implements hook_field_widget_form().
 *
 * hook_widget_form() is where Drupal tells us to create form elements for
 * our field's widget.
 *
 */
function source_id_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $value = isset($items[$delta]['source_id']) ? $items[$delta]['source_id'] : '';

  $widget = $element;
  $widget['#delta'] = $delta;

  switch ($instance['widget']['type']) {
    case 'source_id_widget':
      $widget += array(
        '#type' => 'textfield',
        '#default_value' => $value,
        // Allow a slightly larger size that the field length to allow for some
        // configurations where all characters won't fit in input field.
        '#size' => 10,
        '#maxlength' => 32,
      );
      break;
  }

  $element['source_id'] = $widget;
  return $element;
}

/**
 * Implements hook_field_widget_error().
 *
 * hook_field_widget_error() lets us figure out what to do with errors
 * we might have generated in hook_field_validate(). Generally, we'll just
 * call form_error().
 *
 * @see source_id_field_validate()
 * @see form_error()
 */
function source_id_field_widget_error($element, $error, $form, &$form_state) {
  switch ($error['error']) {
    case 'source_id_field_invalid':
      form_error($element, $error['message']);
      break;
  }
}